services:
  stick-it-server:
    image: lrprojects/stick-it-server:0.0.14
    container_name: stick-it-server
    restart: unless-stopped
    volumes:
      - ./firebase-token.json:/app/firebase-token.json
    env_file:
      - ./.env
    networks:
      - stick-it-network
      - db
      - influxdb-network
      - frontend
    labels:
      - traefik.enable=true
      - traefik.http.routers.stick-it.rule=Host(`stick-it.thinkpad.lr-projects.de`)
      - traefik.http.routers.stick-it.entrypoints=websecure
      - traefik.http.routers.stick-it.tls=true
      - traefik.http.routers.stick-it.tls.certresolver=cloudflare
      - traefik.http.services.stick-it.loadbalancer.server.port=8080
      - traefik.docker.network=frontend
    depends_on:
      - minio

  minio:
    image: minio/minio
    container_name: minio_local
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - ./minio/data:/data # Mount the local directory for data storage
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: ${MINIO_PSW}
    restart: unless-stopped # Optional: Ensure the container restarts on failure or system restart
    command: server /data --console-address ":9001"
    networks:
      - stick-it-network
      - frontend
    labels:
      - traefik.enable=true
      - traefik.docker.network=frontend
      - traefik.http.routers.minio.rule=Host(`minio.thinkpad.lr-projects.de`)
      - traefik.http.routers.minio.entrypoints=websecure
      - traefik.http.routers.minio.tls=true
      - traefik.http.routers.minio.tls.certresolver=cloudflare
      - traefik.http.routers.minio.service=minio
      - traefik.http.services.minio.loadbalancer.server.port=9000
      - traefik.http.routers.minio-admin.rule=Host(`minio-admin.thinkpad.lr-projects.de`)
      - traefik.http.routers.minio-admin.entrypoints=websecure
      - traefik.http.routers.minio-admin.tls=true
      - traefik.http.routers.minio-admin.tls.certresolver=cloudflare
      - traefik.http.routers.minio-admin.service=minio-admin
      - traefik.http.services.minio-admin.loadbalancer.server.port=9001

networks:
  influxdb-network:
    external: true
  stick-it-network:
    external: false
  db:
    external: true
  frontend:
    external: true
