global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
scrape_configs:
  - job_name: adguard-medion
    static_configs:
      - targets: ['adguard-exporter:9617', 'dns-metrics.ionos.lr-projects.de']
  - job_name: 'restic'
    scheme: https
    static_configs:
      - targets: ['restic-metrics.medion.lr-projects.de', 'restic-metrics.thinkpad.lr-projects.de']