http:
  routers:
    adguard:
      rule: "Host(`dns.ionos.lr-projects.de`)"
      entryPoints: websecure
      tls:
        certResolver: cloudflare
      service: adguard-scv
      middlewares:
        - allow-vpn-ips
        - oidc-auth

    traefik-dashboard:
      entryPoints: websecure
      rule: "Host(`traefik.ionos.lr-projects.de`)"
      tls:
        certResolver: cloudflare
      service: api@internal
      middlewares:
        - allow-vpn-ips
        - oidc-auth
      
    adguard-metrics:
      rule: "Host(`dns-metrics.ionos.lr-projects.de`)"
      entryPoints: websecure
      tls:
        certResolver: cloudflare
      service: adguard-metrics-scv
      middlewares:
        - allow-vpn-ips


  services:
    adguard-scv:
      loadBalancer:
        servers:
          - url: "http://adguardhome:80"
  
    adguard-metrics-scv:
      loadBalancer:
        servers:
          - url: "http://adguard-exporter:9617"