http:
  routers:
    pi-hole:
      rule: "Host(`pi-hole.ionos.lr-projects.de`)"
      entryPoints: websecure
      tls:
        certResolver: cloudflare
      service: pi-hole-svc
      middlewares:
        - allow-vpn-ips
        - oidc-auth

    traefik-dashboard:
      entryPoints: websecure
      rule: "Host(`traefik.ionos.lr-projects.de`)"
      tls:
        certResolver: cloudflare
      service: api@internal
      middlewares:
        - allow-vpn-ips
        - oidc-auth
  


  services:
    pi-hole-svc:
      loadBalancer:
        servers:
          - url: "http://pihole:80"
