services:
  db:
    image: postgis/postgis:16-master
    restart: unless-stopped
    container_name: stick-it-db
    labels:
    - com.centurylinklabs.watchtower.enable=true
    annotations:
    - de.lr-projects.description=Stick It postgis database
    - de.lr-projects.sso=false
    volumes:
    - ./postgres-data:/var/lib/postgresql/data
    - ./backup:/backup
    env_file: ./.env
    environment:
    - POSTGRES_PASSWORD=${PG_PASSWORD}
    - POSTGRES_USER=${PG_USER}
    networks:
    - db
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M
networks:
  db:
    external: true
