services:
  glance:
    container_name: glance
    image: glanceapp/glance:latest
    restart: unless-stopped
    volumes:
      - ./config:/app/config
      - ./assets:/app/assets
    networks:
      - frontend
    labels:
      - traefik.enable=true
      - traefik.http.routers.home.rule=Host(`home.thinkpad.lr-projects.de`)
      - traefik.http.routers.home.entrypoints=websecure
      - traefik.http.routers.home.tls=true
      - traefik.http.routers.home.tls.certresolver=cloudflare
      - traefik.http.services.home.loadbalancer.server.port=8080
      - traefik.docker.network=frontend
      - com.centurylinklabs.watchtower.enable=true

networks:
  frontend:
    external: true
