
services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    env_file: .env
    dns:
      - 1.1.1.1
    environment:
      # Only act on containers with this label
      WATCHTOWER_LABEL_ENABLE: "true"
      
      # Schedule: every night at 03:00
      WATCHTOWER_SCHEDULE: 0 0 3 * * *

      # Remove old images after updating
      WATCHTOWER_CLEANUP: "true"

      # Send notification if major update is available
      WATCHTOWER_NOTIFICATIONS: "email"
      WATCHTOWER_NOTIFICATION_EMAIL_FROM: lr.dev.projects@gmail.com
      WATCHTOWER_NOTIFICATION_EMAIL_TO: info@lr-projects.de
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER: smtp.gmail.com
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT: 587
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER: lr.dev.projects@gmail.com
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD: ${EMAIL_PSW}
      WATCHTOWER_NOTIFICATION_EMAIL_SUBJECTTAG: "[Watchtower ${LOCATION}]"
      WATCHTOWER_NOTIFICATION_LEVEL: "info"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
    annotations:
      - de.lr-projects.description=Automated Docker container updates
